name: advanced_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_native_splash: ^2.3.8
  #state management
  bloc: ^8.1.2 
  #Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  #code generator(mainly used with cubit and retrofit)
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  #for dependency injection
  get_it: ^7.6.4
  #localization
  intl: ^0.19.0
  easy_localization: ^3.0.3
  #networking
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts: j
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
